# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_shop_report.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ShopReportPanel(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 859)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(142, 158, 171, 255), stop:1 rgba(238, 242, 243, 255));\n"
"border-radius:10px;")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.drop_shadow_layout.setContentsMargins(0, 0, 0, 0)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color:none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(50, 130, 184);")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_move = QtWidgets.QFrame(self.title_bar)
        self.frame_move.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_move.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_move.setObjectName("frame_move")
        self.horizontalLayout.addWidget(self.frame_move)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color:rgb(255,170,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,170,0,150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_2.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color:rgb(85,255,127);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(85,255,127,150);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_2.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color:rgb(255,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,0,0,150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.drop_shadow_layout.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("background-color:none;")
        self.content_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.content_bar)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_4 = QtWidgets.QFrame(self.content_bar)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dtp_start = QtWidgets.QDateEdit(self.frame_8)
        self.dtp_start.setStyleSheet("QDateEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.dtp_start.setObjectName("dtp_start")
        self.verticalLayout_4.addWidget(self.dtp_start)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.dtp_finish = QtWidgets.QDateEdit(self.frame_9)
        self.dtp_finish.setStyleSheet("QDateEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.dtp_finish.setObjectName("dtp_finish")
        self.verticalLayout_7.addWidget(self.dtp_finish)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_11.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.frame_6.setFont(font)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cmb_shop = QtWidgets.QComboBox(self.frame_7)
        self.cmb_shop.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.cmb_shop.setObjectName("cmb_shop")
        self.verticalLayout_6.addWidget(self.cmb_shop)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.frame_11.setFont(font)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setContentsMargins(7, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.horizontalLayout_7.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cmb_report = QtWidgets.QComboBox(self.frame_12)
        self.cmb_report.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.cmb_report.setObjectName("cmb_report")
        self.cmb_report.addItem("")
        self.cmb_report.setItemText(0, "")
        self.cmb_report.addItem("")
        self.cmb_report.addItem("")
        self.cmb_report.addItem("")
        self.verticalLayout_9.addWidget(self.cmb_report)
        self.horizontalLayout_7.addWidget(self.frame_12)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.verticalLayout_14.addWidget(self.frame_4)
        self.frame_15 = QtWidgets.QFrame(self.content_bar)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 620))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 620))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.frame_19.setFont(font)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.verticalLayout_3.addWidget(self.frame_19)
        self.horizontalLayout_10.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.check_tour_type = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_tour_type.setFont(font)
        self.check_tour_type.setObjectName("check_tour_type")
        self.verticalLayout_13.addWidget(self.check_tour_type)
        self.check_tour_name = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_tour_name.setFont(font)
        self.check_tour_name.setObjectName("check_tour_name")
        self.verticalLayout_13.addWidget(self.check_tour_name)
        self.check_guide = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_guide.setFont(font)
        self.check_guide.setObjectName("check_guide")
        self.verticalLayout_13.addWidget(self.check_guide)
        self.check_note = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_note.setFont(font)
        self.check_note.setObjectName("check_note")
        self.verticalLayout_13.addWidget(self.check_note)
        self.check_operator = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_operator.setFont(font)
        self.check_operator.setObjectName("check_operator")
        self.verticalLayout_13.addWidget(self.check_operator)
        self.check_hotel = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_hotel.setFont(font)
        self.check_hotel.setObjectName("check_hotel")
        self.verticalLayout_13.addWidget(self.check_hotel)
        self.check_pax = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_pax.setFont(font)
        self.check_pax.setObjectName("check_pax")
        self.verticalLayout_13.addWidget(self.check_pax)
        self.check_product = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_product.setFont(font)
        self.check_product.setObjectName("check_product")
        self.verticalLayout_13.addWidget(self.check_product)
        self.check_shop = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_shop.setFont(font)
        self.check_shop.setObjectName("check_shop")
        self.verticalLayout_13.addWidget(self.check_shop)
        self.check_total_kom = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_total_kom.setFont(font)
        self.check_total_kom.setObjectName("check_total_kom")
        self.verticalLayout_13.addWidget(self.check_total_kom)
        self.check_sale = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_sale.setFont(font)
        self.check_sale.setObjectName("check_sale")
        self.verticalLayout_13.addWidget(self.check_sale)
        self.check_operator_kom = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_operator_kom.setFont(font)
        self.check_operator_kom.setObjectName("check_operator_kom")
        self.verticalLayout_13.addWidget(self.check_operator_kom)
        self.check_guide_kom = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_guide_kom.setFont(font)
        self.check_guide_kom.setObjectName("check_guide_kom")
        self.verticalLayout_13.addWidget(self.check_guide_kom)
        self.check_chief_kom = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_chief_kom.setFont(font)
        self.check_chief_kom.setObjectName("check_chief_kom")
        self.verticalLayout_13.addWidget(self.check_chief_kom)
        self.check_driver_kom = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_driver_kom.setFont(font)
        self.check_driver_kom.setObjectName("check_driver_kom")
        self.verticalLayout_13.addWidget(self.check_driver_kom)
        self.check_vip_rep = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_vip_rep.setFont(font)
        self.check_vip_rep.setObjectName("check_vip_rep")
        self.verticalLayout_13.addWidget(self.check_vip_rep)
        self.check_vip_comp = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_vip_comp.setFont(font)
        self.check_vip_comp.setObjectName("check_vip_comp")
        self.verticalLayout_13.addWidget(self.check_vip_comp)
        self.check_landing = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_landing.setFont(font)
        self.check_landing.setObjectName("check_landing")
        self.verticalLayout_13.addWidget(self.check_landing)
        self.check_receive = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_receive.setFont(font)
        self.check_receive.setObjectName("check_receive")
        self.verticalLayout_13.addWidget(self.check_receive)
        self.check_comp_income = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_comp_income.setFont(font)
        self.check_comp_income.setObjectName("check_comp_income")
        self.verticalLayout_13.addWidget(self.check_comp_income)
        self.check_currency = QtWidgets.QCheckBox(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_currency.setFont(font)
        self.check_currency.setObjectName("check_currency")
        self.verticalLayout_13.addWidget(self.check_currency)
        self.horizontalLayout_10.addWidget(self.frame_18)
        self.verticalLayout_14.addWidget(self.frame_15)
        self.frame_20 = QtWidgets.QFrame(self.content_bar)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_16 = QtWidgets.QFrame(self.frame_20)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_22 = QtWidgets.QFrame(self.frame_16)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_11.setContentsMargins(8, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_22)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.horizontalLayout_12.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_16)
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_15.setContentsMargins(11, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.check_short = QtWidgets.QCheckBox(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.check_short.setFont(font)
        self.check_short.setText("")
        self.check_short.setObjectName("check_short")
        self.verticalLayout_15.addWidget(self.check_short)
        self.horizontalLayout_12.addWidget(self.frame_23)
        self.verticalLayout_16.addWidget(self.frame_16)
        self.verticalLayout_14.addWidget(self.frame_20)
        self.frame_13 = QtWidgets.QFrame(self.content_bar)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setContentsMargins(5, 10, 5, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_save = QtWidgets.QPushButton(self.frame_14)
        self.btn_save.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_save.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton {    \n"
"  color: rgb(246, 244, 230);\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 255), stop:1 rgba(61, 114, 180, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 150), stop:1 rgba(61, 114, 180, 150));\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_8.addWidget(self.btn_save)
        self.btn_back = QtWidgets.QPushButton(self.frame_14)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_back.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton {    \n"
"  color: rgb(246, 244, 230);\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 255), stop:1 rgba(61, 114, 180, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 150), stop:1 rgba(61, 114, 180, 150));\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_8.addWidget(self.btn_back)
        self.verticalLayout_10.addWidget(self.frame_14)
        self.verticalLayout_14.addWidget(self.frame_13)
        self.credits_bar = QtWidgets.QFrame(self.content_bar)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits_bar.setStyleSheet("background-color:none;")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_4.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.credits_bar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(50, 130, 184);")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.frame_grip = QtWidgets.QFrame(self.credits_bar)
        self.frame_grip.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_4.addWidget(self.frame_grip)
        self.verticalLayout_14.addWidget(self.credits_bar)
        self.drop_shadow_layout.addWidget(self.content_bar)
        self.verticalLayout_12.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "<strong> TRAVIS </strong> - MAĞAZA RAPORU"))
        self.label_2.setText(_translate("MainWindow", "BAŞLANGIÇ - BİTİŞ TARİHİ"))
        self.label_3.setText(_translate("MainWindow", "MAĞAZA"))
        self.label_4.setText(_translate("MainWindow", "RAPOR TÜRÜ"))
        self.cmb_report.setItemText(1, _translate("MainWindow", "EXCEL"))
        self.cmb_report.setItemText(2, _translate("MainWindow", "PDF"))
        self.cmb_report.setItemText(3, _translate("MainWindow", "GRAFİK"))
        self.label_5.setText(_translate("MainWindow", "KOLONLAR"))
        self.check_tour_type.setText(_translate("MainWindow", "Tur Türü"))
        self.check_tour_name.setText(_translate("MainWindow", "Tur Adı"))
        self.check_guide.setText(_translate("MainWindow", "Rehber"))
        self.check_note.setText(_translate("MainWindow", "Note"))
        self.check_operator.setText(_translate("MainWindow", "Operatör"))
        self.check_hotel.setText(_translate("MainWindow", "Otel"))
        self.check_pax.setText(_translate("MainWindow", "Pax"))
        self.check_product.setText(_translate("MainWindow", "Ürün"))
        self.check_shop.setText(_translate("MainWindow", "Mağaza"))
        self.check_total_kom.setText(_translate("MainWindow", "Toplam Komisyon"))
        self.check_sale.setText(_translate("MainWindow", "Satış"))
        self.check_operator_kom.setText(_translate("MainWindow", "Operatör Komisyon"))
        self.check_guide_kom.setText(_translate("MainWindow", "Rehber Komisyon"))
        self.check_chief_kom.setText(_translate("MainWindow", "Şef Komisyon"))
        self.check_driver_kom.setText(_translate("MainWindow", "Şoför Komisyon"))
        self.check_vip_rep.setText(_translate("MainWindow", "Vip Rep"))
        self.check_vip_comp.setText(_translate("MainWindow", "Vip Şirket"))
        self.check_landing.setText(_translate("MainWindow", "Ayak Bastı"))
        self.check_receive.setText(_translate("MainWindow", "Tahsil Tutarı"))
        self.check_comp_income.setText(_translate("MainWindow", "Şirket Girdisi"))
        self.check_currency.setText(_translate("MainWindow", "Para Birimi"))
        self.label_6.setText(_translate("MainWindow", "ÖZET RAPOR AL"))
        self.btn_save.setText(_translate("MainWindow", "Rapor Al"))
        self.btn_back.setText(_translate("MainWindow", "Geri"))
        self.label.setText(_translate("MainWindow", "Powered By TRAVEYO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ShopReportPanel()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

