# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_shop_sale.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ShopSalePanel(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1543, 928)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(142, 158, 171, 255), stop:1 rgba(238, 242, 243, 255));\n"
"border-radius:10px;")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_bar.setFont(font)
        self.title_bar.setStyleSheet("background-color:none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(5, 4, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_title.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setMinimumSize(QtCore.QSize(0, 0))
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(50, 130, 184);")
        self.label_title.setIndent(0)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_move = QtWidgets.QFrame(self.title_bar)
        self.frame_move.setMinimumSize(QtCore.QSize(45, 15))
        self.frame_move.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_move.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_move.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_move.setObjectName("frame_move")
        self.horizontalLayout.addWidget(self.frame_move)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 40))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color:rgb(255,170,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255,170,0,150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_4.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color:rgb(85,255,127);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(85,255,127,150);\n"
"}\n"
"")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_4.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 0, 0,150);\n"
"}\n"
"")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_4.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout_19.addWidget(self.title_bar)
        self.frame = QtWidgets.QFrame(self.drop_shadow_frame)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("background-color:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(7, 0, 7, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_calculate = QtWidgets.QPushButton(self.frame)
        self.btn_calculate.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_calculate.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calculate.setFont(font)
        self.btn_calculate.setStyleSheet("QPushButton {    \n"
"  color: rgb(246, 244, 230);\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 255), stop:1 rgba(61, 114, 180, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 150), stop:1 rgba(61, 114, 180, 150));\n"
"}")
        self.btn_calculate.setObjectName("btn_calculate")
        self.horizontalLayout_3.addWidget(self.btn_calculate)
        self.btn_delete = QtWidgets.QPushButton(self.frame)
        self.btn_delete.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_delete.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("QPushButton {    \n"
"  color: rgb(246, 244, 230);\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 255), stop:1 rgba(61, 114, 180, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 150), stop:1 rgba(61, 114, 180, 150));\n"
"}")
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_3.addWidget(self.btn_delete)
        spacerItem = QtWidgets.QSpacerItem(367, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(self.frame)
        self.btn_save.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_save.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton {    \n"
"  color: rgb(246, 244, 230);\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 255), stop:1 rgba(61, 114, 180, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 150), stop:1 rgba(61, 114, 180, 150));\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_3.addWidget(self.btn_save)
        self.btn_back = QtWidgets.QPushButton(self.frame)
        self.btn_back.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_back.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton {    \n"
"  color: rgb(246, 244, 230);\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 255), stop:1 rgba(61, 114, 180, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 150), stop:1 rgba(61, 114, 180, 150));\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_3.addWidget(self.btn_back)
        self.verticalLayout_19.addWidget(self.frame)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("background-color:none;")
        self.content_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.content_bar)
        self.horizontalLayout_10.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_24 = QtWidgets.QFrame(self.content_bar)
        self.frame_24.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_3 = QtWidgets.QFrame(self.frame_24)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 255), stop:1 rgba(61, 114, 180, 255));\n"
"    background-color: transparent;\n"
"    border-radius:10px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout_8.addWidget(self.tableWidget)
        self.verticalLayout_18.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_24)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 350))
        self.frame_4.setStyleSheet("background-color:transparent;\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setStyleSheet("color: rgb(50, 130, 184);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dtp_start = QtWidgets.QDateEdit(self.frame_10)
        self.dtp_start.setStyleSheet("QDateEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:white;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.dtp_start.setObjectName("dtp_start")
        self.verticalLayout_6.addWidget(self.dtp_start)
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.dtp_finish = QtWidgets.QDateEdit(self.frame_11)
        self.dtp_finish.setStyleSheet("QDateEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:white;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.dtp_finish.setObjectName("dtp_finish")
        self.verticalLayout_7.addWidget(self.dtp_finish)
        self.horizontalLayout_5.addWidget(self.frame_11)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_5 = QtWidgets.QLabel(self.frame_21)
        self.label_5.setStyleSheet("color: rgb(50, 130, 184);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_16.addWidget(self.label_5)
        self.verticalLayout_15.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.cmb_tour_type = QtWidgets.QComboBox(self.frame_23)
        self.cmb_tour_type.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}\n"
"QAbstractItemView{background:white;border:none;}")
        self.cmb_tour_type.setObjectName("cmb_tour_type")
        self.cmb_tour_type.addItem("")
        self.cmb_tour_type.setItemText(0, "")
        self.cmb_tour_type.addItem("")
        self.cmb_tour_type.addItem("")
        self.cmb_tour_type.addItem("")
        self.verticalLayout_17.addWidget(self.cmb_tour_type)
        self.horizontalLayout_8.addWidget(self.frame_23)
        self.verticalLayout_15.addWidget(self.frame_22)
        self.verticalLayout_3.addWidget(self.frame_20)
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.frame_13)
        self.label_3.setStyleSheet("color: rgb(50, 130, 184);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.cmb_shop = QtWidgets.QComboBox(self.frame_16)
        self.cmb_shop.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}\n"
"QAbstractItemView{background:white;border:none;}")
        self.cmb_shop.setObjectName("cmb_shop")
        self.verticalLayout_12.addWidget(self.cmb_shop)
        self.horizontalLayout_6.addWidget(self.frame_16)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.frame_15 = QtWidgets.QFrame(self.frame_4)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_4 = QtWidgets.QLabel(self.frame_17)
        self.label_4.setStyleSheet("color: rgb(50, 130, 184);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4)
        self.verticalLayout_11.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.cmb_guide = QtWidgets.QComboBox(self.frame_19)
        self.cmb_guide.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}\n"
"QAbstractItemView{background:white;border:none;}")
        self.cmb_guide.setObjectName("cmb_guide")
        self.verticalLayout_14.addWidget(self.cmb_guide)
        self.horizontalLayout_7.addWidget(self.frame_19)
        self.verticalLayout_11.addWidget(self.frame_18)
        self.verticalLayout_3.addWidget(self.frame_15)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_search = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_search.sizePolicy().hasHeightForWidth())
        self.btn_search.setSizePolicy(sizePolicy)
        self.btn_search.setMaximumSize(QtCore.QSize(1312313, 16777215))
        self.btn_search.setStyleSheet("QPushButton {    \n"
"  color: rgb(246, 244, 230);\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 255), stop:1 rgba(61, 114, 180, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(82, 82, 82, 150), stop:1 rgba(61, 114, 180, 150));\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_9.addWidget(self.btn_search)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_18.addWidget(self.frame_4)
        self.horizontalLayout_10.addWidget(self.frame_24)
        self.frame_5 = QtWidgets.QFrame(self.content_bar)
        self.frame_5.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(700, 16777215))
        self.frame_5.setStyleSheet("background-color:transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_25 = QtWidgets.QFrame(self.frame_5)
        self.frame_25.setMaximumSize(QtCore.QSize(850, 16777215))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_47.setSpacing(0)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_38 = QtWidgets.QLabel(self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: black;")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_47.addWidget(self.label_38)
        self.horizontalLayout_11.addWidget(self.frame_27)
        self.frame_97 = QtWidgets.QFrame(self.frame_26)
        self.frame_97.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_97.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_97.setObjectName("frame_97")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.frame_97)
        self.verticalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_48.setSpacing(0)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.cmb_guide_2 = QtWidgets.QComboBox(self.frame_97)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.cmb_guide_2.setFont(font)
        self.cmb_guide_2.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}\n"
"QAbstractItemView{background:white;border:none;}")
        self.cmb_guide_2.setCurrentText("")
        self.cmb_guide_2.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cmb_guide_2.setObjectName("cmb_guide_2")
        self.verticalLayout_48.addWidget(self.cmb_guide_2)
        self.horizontalLayout_11.addWidget(self.frame_97)
        self.verticalLayout_20.addWidget(self.frame_26)
        self.frame_28 = QtWidgets.QFrame(self.frame_25)
        self.frame_28.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_28.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_98 = QtWidgets.QFrame(self.frame_28)
        self.frame_98.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_98.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_98.setObjectName("frame_98")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.frame_98)
        self.verticalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_49.setSpacing(0)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.label_39 = QtWidgets.QLabel(self.frame_98)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: black;")
        self.label_39.setObjectName("label_39")
        self.verticalLayout_49.addWidget(self.label_39)
        self.horizontalLayout_12.addWidget(self.frame_98)
        self.frame_99 = QtWidgets.QFrame(self.frame_28)
        self.frame_99.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_99.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_99.setObjectName("frame_99")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.frame_99)
        self.verticalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_50.setSpacing(0)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.cmb_shop_2 = QtWidgets.QComboBox(self.frame_99)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.cmb_shop_2.setFont(font)
        self.cmb_shop_2.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}\n"
"QAbstractItemView{background:white;border:none;}")
        self.cmb_shop_2.setCurrentText("")
        self.cmb_shop_2.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cmb_shop_2.setObjectName("cmb_shop_2")
        self.verticalLayout_50.addWidget(self.cmb_shop_2)
        self.horizontalLayout_12.addWidget(self.frame_99)
        self.verticalLayout_20.addWidget(self.frame_28)
        self.frame_29 = QtWidgets.QFrame(self.frame_25)
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label = QtWidgets.QLabel(self.frame_29)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black;")
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        self.dtp_sale = QtWidgets.QDateEdit(self.frame_29)
        self.dtp_sale.setStyleSheet("QDateEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.dtp_sale.setObjectName("dtp_sale")
        self.horizontalLayout_13.addWidget(self.dtp_sale)
        self.verticalLayout_20.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_25)
        self.frame_30.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_100 = QtWidgets.QFrame(self.frame_30)
        self.frame_100.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_100.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_100.setObjectName("frame_100")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.frame_100)
        self.verticalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_51.setSpacing(0)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.label_40 = QtWidgets.QLabel(self.frame_100)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: black;")
        self.label_40.setObjectName("label_40")
        self.verticalLayout_51.addWidget(self.label_40)
        self.horizontalLayout_15.addWidget(self.frame_100)
        self.frame_31 = QtWidgets.QFrame(self.frame_30)
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_52.setSpacing(0)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.cmb_product = QtWidgets.QComboBox(self.frame_31)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.cmb_product.setFont(font)
        self.cmb_product.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}\n"
"QAbstractItemView{background:white;border:none;}")
        self.cmb_product.setCurrentText("")
        self.cmb_product.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cmb_product.setObjectName("cmb_product")
        self.verticalLayout_52.addWidget(self.cmb_product)
        self.horizontalLayout_15.addWidget(self.frame_31)
        self.verticalLayout_20.addWidget(self.frame_30)
        self.frame_74 = QtWidgets.QFrame(self.frame_25)
        self.frame_74.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_74.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_74.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_74.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_74.setObjectName("frame_74")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_74)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_75 = QtWidgets.QFrame(self.frame_74)
        self.frame_75.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_75.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_75.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_75.setObjectName("frame_75")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.frame_75)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setSpacing(0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.frame_77 = QtWidgets.QFrame(self.frame_75)
        self.frame_77.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_77.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_77.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_77.setObjectName("frame_77")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_77)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_32 = QtWidgets.QFrame(self.frame_77)
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.frame_32.setFont(font)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_31 = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_31.addWidget(self.label_31)
        self.verticalLayout_21.addWidget(self.frame_32)
        self.frame_84 = QtWidgets.QFrame(self.frame_77)
        self.frame_84.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_84.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_84.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_84.setObjectName("frame_84")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_84)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.txt_def_guide_rate = QtWidgets.QLineEdit(self.frame_84)
        self.txt_def_guide_rate.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:white;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_def_guide_rate.setObjectName("txt_def_guide_rate")
        self.verticalLayout_38.addWidget(self.txt_def_guide_rate)
        self.verticalLayout_21.addWidget(self.frame_84)
        self.horizontalLayout_47.addWidget(self.frame_77)
        self.frame_78 = QtWidgets.QFrame(self.frame_75)
        self.frame_78.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_78.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_78.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_78.setObjectName("frame_78")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_78)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_85 = QtWidgets.QFrame(self.frame_78)
        self.frame_85.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_85.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_85.setObjectName("frame_85")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_85)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_32 = QtWidgets.QLabel(self.frame_85)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_33.addWidget(self.label_32)
        self.verticalLayout_32.addWidget(self.frame_85)
        self.frame_86 = QtWidgets.QFrame(self.frame_78)
        self.frame_86.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_86.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_86.setObjectName("frame_86")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_86)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.txt_def_driver_rate = QtWidgets.QLineEdit(self.frame_86)
        self.txt_def_driver_rate.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:white;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_def_driver_rate.setObjectName("txt_def_driver_rate")
        self.verticalLayout_39.addWidget(self.txt_def_driver_rate)
        self.verticalLayout_32.addWidget(self.frame_86)
        self.horizontalLayout_47.addWidget(self.frame_78)
        self.frame_79 = QtWidgets.QFrame(self.frame_75)
        self.frame_79.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_79.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_79.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_79.setObjectName("frame_79")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_79)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.frame_87 = QtWidgets.QFrame(self.frame_79)
        self.frame_87.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_87.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_87.setObjectName("frame_87")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_87)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_33 = QtWidgets.QLabel(self.frame_87)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_35.addWidget(self.label_33)
        self.verticalLayout_34.addWidget(self.frame_87)
        self.frame_88 = QtWidgets.QFrame(self.frame_79)
        self.frame_88.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_88.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_88.setObjectName("frame_88")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_88)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.txt_def_opr_rate = QtWidgets.QLineEdit(self.frame_88)
        self.txt_def_opr_rate.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:white;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_def_opr_rate.setObjectName("txt_def_opr_rate")
        self.verticalLayout_40.addWidget(self.txt_def_opr_rate)
        self.verticalLayout_34.addWidget(self.frame_88)
        self.horizontalLayout_47.addWidget(self.frame_79)
        self.frame_80 = QtWidgets.QFrame(self.frame_75)
        self.frame_80.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_80.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_80.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_80.setObjectName("frame_80")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_80)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.frame_89 = QtWidgets.QFrame(self.frame_80)
        self.frame_89.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_89.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_89.setObjectName("frame_89")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_89)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_34 = QtWidgets.QLabel(self.frame_89)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_37.addWidget(self.label_34)
        self.verticalLayout_36.addWidget(self.frame_89)
        self.frame_90 = QtWidgets.QFrame(self.frame_80)
        self.frame_90.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_90.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_90.setObjectName("frame_90")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.frame_90)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.txt_def_reo_rate = QtWidgets.QLineEdit(self.frame_90)
        self.txt_def_reo_rate.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:white;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_def_reo_rate.setObjectName("txt_def_reo_rate")
        self.verticalLayout_41.addWidget(self.txt_def_reo_rate)
        self.verticalLayout_36.addWidget(self.frame_90)
        self.horizontalLayout_47.addWidget(self.frame_80)
        self.verticalLayout_30.addWidget(self.frame_75)
        self.frame_76 = QtWidgets.QFrame(self.frame_74)
        self.frame_76.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_76.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_76.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_76.setObjectName("frame_76")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.frame_76)
        self.horizontalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_48.setSpacing(0)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.frame_81 = QtWidgets.QFrame(self.frame_76)
        self.frame_81.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_81.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_81.setObjectName("frame_81")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_81)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_91 = QtWidgets.QFrame(self.frame_81)
        self.frame_91.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_91.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_91.setObjectName("frame_91")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.frame_91)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_35 = QtWidgets.QLabel(self.frame_91)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_44.addWidget(self.label_35)
        self.verticalLayout_22.addWidget(self.frame_91)
        self.frame_92 = QtWidgets.QFrame(self.frame_81)
        self.frame_92.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_92.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_92.setObjectName("frame_92")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.frame_92)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.txt_def_guide_rate_2 = QtWidgets.QLineEdit(self.frame_92)
        self.txt_def_guide_rate_2.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:white;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_def_guide_rate_2.setObjectName("txt_def_guide_rate_2")
        self.horizontalLayout_50.addWidget(self.txt_def_guide_rate_2)
        self.verticalLayout_22.addWidget(self.frame_92)
        self.horizontalLayout_48.addWidget(self.frame_81)
        self.frame_82 = QtWidgets.QFrame(self.frame_76)
        self.frame_82.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_82.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_82.setObjectName("frame_82")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.frame_82)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_42.setSpacing(0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.frame_93 = QtWidgets.QFrame(self.frame_82)
        self.frame_93.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_93.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_93.setObjectName("frame_93")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.frame_93)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_36 = QtWidgets.QLabel(self.frame_93)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_45.addWidget(self.label_36)
        self.verticalLayout_42.addWidget(self.frame_93)
        self.frame_94 = QtWidgets.QFrame(self.frame_82)
        self.frame_94.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_94.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_94.setObjectName("frame_94")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.frame_94)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.txt_def_guide_rate_3 = QtWidgets.QLineEdit(self.frame_94)
        self.txt_def_guide_rate_3.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:white;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_def_guide_rate_3.setObjectName("txt_def_guide_rate_3")
        self.horizontalLayout_51.addWidget(self.txt_def_guide_rate_3)
        self.verticalLayout_42.addWidget(self.frame_94)
        self.horizontalLayout_48.addWidget(self.frame_82)
        self.frame_83 = QtWidgets.QFrame(self.frame_76)
        self.frame_83.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_83.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_83.setObjectName("frame_83")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_83)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setSpacing(0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.frame_95 = QtWidgets.QFrame(self.frame_83)
        self.frame_95.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_95.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_95.setObjectName("frame_95")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.frame_95)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.label_37 = QtWidgets.QLabel(self.frame_95)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_46.addWidget(self.label_37)
        self.verticalLayout_43.addWidget(self.frame_95)
        self.frame_96 = QtWidgets.QFrame(self.frame_83)
        self.frame_96.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_96.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_96.setObjectName("frame_96")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.frame_96)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.txt_def_guide_rate_4 = QtWidgets.QLineEdit(self.frame_96)
        self.txt_def_guide_rate_4.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:white;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_def_guide_rate_4.setObjectName("txt_def_guide_rate_4")
        self.horizontalLayout_52.addWidget(self.txt_def_guide_rate_4)
        self.verticalLayout_43.addWidget(self.frame_96)
        self.horizontalLayout_48.addWidget(self.frame_83)
        self.verticalLayout_30.addWidget(self.frame_76)
        self.verticalLayout_20.addWidget(self.frame_74)
        self.frame_33 = QtWidgets.QFrame(self.frame_25)
        self.frame_33.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.txt_tour_name = QtWidgets.QLineEdit(self.frame_33)
        self.txt_tour_name.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txt_tour_name.setFont(font)
        self.txt_tour_name.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_tour_name.setText("")
        self.txt_tour_name.setObjectName("txt_tour_name")
        self.horizontalLayout_14.addWidget(self.txt_tour_name)
        self.verticalLayout_20.addWidget(self.frame_33)
        self.frame_34 = QtWidgets.QFrame(self.frame_25)
        self.frame_34.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_34.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_102 = QtWidgets.QFrame(self.frame_34)
        self.frame_102.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_102.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_102.setObjectName("frame_102")
        self.verticalLayout_54 = QtWidgets.QVBoxLayout(self.frame_102)
        self.verticalLayout_54.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_54.setSpacing(0)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.label_41 = QtWidgets.QLabel(self.frame_102)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: black;")
        self.label_41.setObjectName("label_41")
        self.verticalLayout_54.addWidget(self.label_41)
        self.horizontalLayout_16.addWidget(self.frame_102)
        self.frame_101 = QtWidgets.QFrame(self.frame_34)
        self.frame_101.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_101.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_101.setObjectName("frame_101")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout(self.frame_101)
        self.verticalLayout_53.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_53.setSpacing(0)
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.cmb_tour_type_2 = QtWidgets.QComboBox(self.frame_101)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.cmb_tour_type_2.setFont(font)
        self.cmb_tour_type_2.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}\n"
"QAbstractItemView{background:white;border:none;}")
        self.cmb_tour_type_2.setCurrentText("")
        self.cmb_tour_type_2.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cmb_tour_type_2.setObjectName("cmb_tour_type_2")
        self.cmb_tour_type_2.addItem("")
        self.cmb_tour_type_2.setItemText(0, "")
        self.cmb_tour_type_2.addItem("")
        self.cmb_tour_type_2.addItem("")
        self.cmb_tour_type_2.addItem("")
        self.verticalLayout_53.addWidget(self.cmb_tour_type_2)
        self.horizontalLayout_16.addWidget(self.frame_101)
        self.verticalLayout_20.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.frame_25)
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.txt_hotel = QtWidgets.QLineEdit(self.frame_35)
        self.txt_hotel.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txt_hotel.setFont(font)
        self.txt_hotel.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_hotel.setText("")
        self.txt_hotel.setObjectName("txt_hotel")
        self.horizontalLayout_17.addWidget(self.txt_hotel)
        self.verticalLayout_20.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(self.frame_25)
        self.frame_36.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_36.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_103 = QtWidgets.QFrame(self.frame_36)
        self.frame_103.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_103.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_103.setObjectName("frame_103")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.frame_103)
        self.verticalLayout_55.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_55.setSpacing(0)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.label_42 = QtWidgets.QLabel(self.frame_103)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: black;")
        self.label_42.setObjectName("label_42")
        self.verticalLayout_55.addWidget(self.label_42)
        self.horizontalLayout_18.addWidget(self.frame_103)
        self.frame_104 = QtWidgets.QFrame(self.frame_36)
        self.frame_104.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_104.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_104.setObjectName("frame_104")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout(self.frame_104)
        self.verticalLayout_56.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_56.setSpacing(0)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.cmb_operator = QtWidgets.QComboBox(self.frame_104)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.cmb_operator.setFont(font)
        self.cmb_operator.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}\n"
"QAbstractItemView{background:white;border:none;}")
        self.cmb_operator.setCurrentText("")
        self.cmb_operator.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cmb_operator.setObjectName("cmb_operator")
        self.verticalLayout_56.addWidget(self.cmb_operator)
        self.horizontalLayout_18.addWidget(self.frame_104)
        self.verticalLayout_20.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.frame_25)
        self.frame_37.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_37.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.txt_pax = QtWidgets.QLineEdit(self.frame_37)
        self.txt_pax.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txt_pax.setFont(font)
        self.txt_pax.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_pax.setText("")
        self.txt_pax.setObjectName("txt_pax")
        self.horizontalLayout_19.addWidget(self.txt_pax)
        self.verticalLayout_20.addWidget(self.frame_37)
        self.frame_38 = QtWidgets.QFrame(self.frame_25)
        self.frame_38.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.txt_total_sale = QtWidgets.QLineEdit(self.frame_38)
        self.txt_total_sale.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txt_total_sale.setFont(font)
        self.txt_total_sale.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_total_sale.setText("")
        self.txt_total_sale.setObjectName("txt_total_sale")
        self.horizontalLayout_20.addWidget(self.txt_total_sale)
        self.verticalLayout_20.addWidget(self.frame_38)
        self.frame_39 = QtWidgets.QFrame(self.frame_25)
        self.frame_39.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_39)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_105 = QtWidgets.QFrame(self.frame_39)
        self.frame_105.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_105.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_105.setObjectName("frame_105")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout(self.frame_105)
        self.verticalLayout_57.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_57.setSpacing(0)
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.label_43 = QtWidgets.QLabel(self.frame_105)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: black;")
        self.label_43.setObjectName("label_43")
        self.verticalLayout_57.addWidget(self.label_43)
        self.horizontalLayout_21.addWidget(self.frame_105)
        self.frame_106 = QtWidgets.QFrame(self.frame_39)
        self.frame_106.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_106.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_106.setObjectName("frame_106")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.frame_106)
        self.verticalLayout_58.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_58.setSpacing(0)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.cmb_currency = QtWidgets.QComboBox(self.frame_106)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.cmb_currency.setFont(font)
        self.cmb_currency.setStyleSheet("QComboBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}\n"
"QAbstractItemView{background:white;border:none;}")
        self.cmb_currency.setCurrentText("")
        self.cmb_currency.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cmb_currency.setObjectName("cmb_currency")
        self.cmb_currency.addItem("")
        self.cmb_currency.setItemText(0, "")
        self.cmb_currency.addItem("")
        self.cmb_currency.addItem("")
        self.cmb_currency.addItem("")
        self.cmb_currency.addItem("")
        self.verticalLayout_58.addWidget(self.cmb_currency)
        self.horizontalLayout_21.addWidget(self.frame_106)
        self.verticalLayout_20.addWidget(self.frame_39)
        self.frame_40 = QtWidgets.QFrame(self.frame_25)
        self.frame_40.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_40.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.check_forward = QtWidgets.QCheckBox(self.frame_40)
        self.check_forward.setStyleSheet("QCheckBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.check_forward.setObjectName("check_forward")
        self.horizontalLayout_22.addWidget(self.check_forward)
        self.frame_41 = QtWidgets.QFrame(self.frame_40)
        self.frame_41.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frame_42 = QtWidgets.QFrame(self.frame_41)
        self.frame_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_6 = QtWidgets.QLabel(self.frame_42)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: black;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_23.addWidget(self.label_6)
        self.horizontalLayout_23.addWidget(self.frame_42)
        self.frame_43 = QtWidgets.QFrame(self.frame_41)
        self.frame_43.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_43)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.dtp_forward = QtWidgets.QDateEdit(self.frame_43)
        self.dtp_forward.setStyleSheet("QDateEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.dtp_forward.setObjectName("dtp_forward")
        self.verticalLayout_24.addWidget(self.dtp_forward)
        self.horizontalLayout_23.addWidget(self.frame_43)
        self.horizontalLayout_22.addWidget(self.frame_41)
        self.verticalLayout_20.addWidget(self.frame_40)
        self.frame_44 = QtWidgets.QFrame(self.frame_25)
        self.frame_44.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_44.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_44)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.check_vip = QtWidgets.QCheckBox(self.frame_44)
        self.check_vip.setStyleSheet("QCheckBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.check_vip.setObjectName("check_vip")
        self.horizontalLayout_24.addWidget(self.check_vip)
        self.check_landing = QtWidgets.QCheckBox(self.frame_44)
        self.check_landing.setStyleSheet("QCheckBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.check_landing.setObjectName("check_landing")
        self.horizontalLayout_24.addWidget(self.check_landing)
        self.check_chief = QtWidgets.QCheckBox(self.frame_44)
        self.check_chief.setStyleSheet("QCheckBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.check_chief.setObjectName("check_chief")
        self.horizontalLayout_24.addWidget(self.check_chief)
        self.check_received = QtWidgets.QCheckBox(self.frame_44)
        self.check_received.setStyleSheet("QCheckBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.check_received.setObjectName("check_received")
        self.horizontalLayout_24.addWidget(self.check_received)
        self.check_money_on_guide = QtWidgets.QCheckBox(self.frame_44)
        self.check_money_on_guide.setStyleSheet("QCheckBox{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.check_money_on_guide.setObjectName("check_money_on_guide")
        self.horizontalLayout_24.addWidget(self.check_money_on_guide)
        self.verticalLayout_20.addWidget(self.frame_44)
        self.frame_45 = QtWidgets.QFrame(self.frame_25)
        self.frame_45.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_45.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_45)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.txt_rate = QtWidgets.QLineEdit(self.frame_45)
        self.txt_rate.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txt_rate.setFont(font)
        self.txt_rate.setStyleSheet("QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_rate.setText("")
        self.txt_rate.setObjectName("txt_rate")
        self.horizontalLayout_25.addWidget(self.txt_rate)
        self.verticalLayout_20.addWidget(self.frame_45)
        self.frame_46 = QtWidgets.QFrame(self.frame_25)
        self.frame_46.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.txt_note = QtWidgets.QTextEdit(self.frame_46)
        self.txt_note.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txt_note.setFont(font)
        self.txt_note.setStyleSheet("QTextEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: black;\n"
"    border-bottom:1px solid #717072\n"
"}")
        self.txt_note.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_note.setObjectName("txt_note")
        self.verticalLayout_25.addWidget(self.txt_note)
        self.verticalLayout_20.addWidget(self.frame_46)
        self.verticalLayout_26.addWidget(self.frame_25)
        self.frame_grip = QtWidgets.QFrame(self.frame_5)
        self.frame_grip.setMinimumSize(QtCore.QSize(16777215, 30))
        self.frame_grip.setMaximumSize(QtCore.QSize(13213213, 30))
        self.frame_grip.setStyleSheet("padding:5px;background-color:none;")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_grip)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_grip)
        self.frame_2.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_2.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_26.addWidget(self.frame_grip)
        self.horizontalLayout_10.addWidget(self.frame_5)
        self.verticalLayout_19.addWidget(self.content_bar)
        self.verticalLayout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cmb_guide_2.setCurrentIndex(-1)
        self.cmb_shop_2.setCurrentIndex(-1)
        self.cmb_product.setCurrentIndex(-1)
        self.cmb_tour_type_2.setCurrentIndex(0)
        self.cmb_operator.setCurrentIndex(-1)
        self.cmb_currency.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "<strong>TRAVIS </strong> - Satışlar"))
        self.btn_calculate.setText(_translate("MainWindow", "Hesaplat"))
        self.btn_delete.setText(_translate("MainWindow", "Sil"))
        self.btn_save.setText(_translate("MainWindow", "Kaydet"))
        self.btn_back.setText(_translate("MainWindow", "Geri"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SATIŞ TARİHİ"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "REHBER"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MAĞAZA"))
        self.label_2.setText(_translate("MainWindow", "BAŞLANGIÇ - BİTİŞ"))
        self.label_5.setText(_translate("MainWindow", "TUR TÜRÜ"))
        self.cmb_tour_type.setItemText(1, _translate("MainWindow", "VIP"))
        self.cmb_tour_type.setItemText(2, _translate("MainWindow", "GRUP"))
        self.cmb_tour_type.setItemText(3, _translate("MainWindow", "ANADOLU TURU"))
        self.label_3.setText(_translate("MainWindow", "MAĞAZA"))
        self.label_4.setText(_translate("MainWindow", "REHBER"))
        self.btn_search.setText(_translate("MainWindow", "Listele"))
        self.label_38.setText(_translate("MainWindow", "REHBER"))
        self.label_39.setText(_translate("MainWindow", "MAĞAZA"))
        self.label.setText(_translate("MainWindow", "SATIŞ TARİHİ "))
        self.label_40.setText(_translate("MainWindow", "ÜRÜN"))
        self.label_31.setText(_translate("MainWindow", "REHBER "))
        self.label_32.setText(_translate("MainWindow", "ŞOFÖR"))
        self.label_33.setText(_translate("MainWindow", "OPERATÖR"))
        self.label_34.setText(_translate("MainWindow", "REP"))
        self.label_35.setText(_translate("MainWindow", "TOPLAM"))
        self.label_36.setText(_translate("MainWindow", "ŞİRKET (KOKARTLI)"))
        self.label_37.setText(_translate("MainWindow", "ŞİRKET (REP)"))
        self.txt_tour_name.setPlaceholderText(_translate("MainWindow", "TUR ADI"))
        self.label_41.setText(_translate("MainWindow", "TUR TÜRÜ"))
        self.cmb_tour_type_2.setItemText(1, _translate("MainWindow", "VIP"))
        self.cmb_tour_type_2.setItemText(2, _translate("MainWindow", "GRUP"))
        self.cmb_tour_type_2.setItemText(3, _translate("MainWindow", "ANADOLU TURU"))
        self.txt_hotel.setPlaceholderText(_translate("MainWindow", "OTEL ADI"))
        self.label_42.setText(_translate("MainWindow", "OPERATÖR"))
        self.txt_pax.setPlaceholderText(_translate("MainWindow", "PAX"))
        self.txt_total_sale.setPlaceholderText(_translate("MainWindow", "TOPLAM SATIŞ"))
        self.label_43.setText(_translate("MainWindow", "PARA BİRİMİ"))
        self.cmb_currency.setItemText(1, _translate("MainWindow", "EUR"))
        self.cmb_currency.setItemText(2, _translate("MainWindow", "USD"))
        self.cmb_currency.setItemText(3, _translate("MainWindow", "TRY"))
        self.cmb_currency.setItemText(4, _translate("MainWindow", "GBP"))
        self.check_forward.setText(_translate("MainWindow", "VADELİ SATIŞ"))
        self.label_6.setText(_translate("MainWindow", "VADE TARİHİ "))
        self.check_vip.setText(_translate("MainWindow", "VİP KOM"))
        self.check_landing.setText(_translate("MainWindow", "AYAK BASTI"))
        self.check_chief.setText(_translate("MainWindow", "ŞEF KOM"))
        self.check_received.setText(_translate("MainWindow", "TAHSİL"))
        self.check_money_on_guide.setText(_translate("MainWindow", "PARA REHBERDE"))
        self.txt_rate.setPlaceholderText(_translate("MainWindow", "EUR KURU"))
        self.txt_note.setPlaceholderText(_translate("MainWindow", "NOT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ShopSalePanel()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

